// Audit the actual source with synthetic data. Repository I/O is redirected to memory.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript'),bcrypt=require('bcryptjs');
const base=path.resolve(__dirname,'..');
const output=path.join(base,'audit-results');fs.mkdirSync(output,{recursive:true});
const password='Synthetic-Test-Only-42!';const hash=bcrypt.hashSync(password,4);
process.env.TZ='Asia/Ho_Chi_Minh';
const now=Date.now(),iso=offset=>new Date(now+offset).toISOString();
const members=[
 ['admin','Admin Test','admin','A'],['manager-a','Manager A','tpkd','A'],['manager-b','Manager B','tpkd','B'],
 ['sale-a','Sale A','sale','A'],['sale-a2','Sale A2','sale','A'],['sale-b','Sale B','sale','B'],
 ['paused','Paused Sale','sale','B'],['manager-no-team','Manager Missing Team','tpkd',undefined]
].map(([id,name,role,team],index)=>({id,name,role,team,teamId:team,username:id,email:id+'@audit.invalid',phone:'0000000'+String(index).padStart(3,'0'),passwordHash:hash,status:id==='paused'?'paused':'active',isOnlineForLead:true,maxDailyLeads:2,managerId:role==='sale'?'manager-'+team?.toLowerCase():undefined,managerEmail:role==='sale'?'manager-'+team?.toLowerCase()+'@audit.invalid':undefined,title:role}));
const statuses=['Khách mới','Đang chăm sóc','Quan tâm','Hẹn xem BĐS','Đàm phán / Cọc','Đã chốt','Tiềm năng','Không nhu cầu'];
const leads=Array.from({length:40},(_,index)=>{
 const owner=members[3+index%3];return {id:'lead-'+index,stt:index+1,fullName:'Synthetic Customer '+index,phone:'00000'+String(index).padStart(5,'0'),email:'customer'+index+'@audit.invalid',assignee:owner.name,assignedToId:owner.id,assigneeEmail:owner.email,team:owner.team,status:statuses[index%statuses.length],date:new Date(now).toISOString().slice(0,10),project:'Synthetic project',budget:'2 tỷ',notes:'Synthetic data',dataSource:'Audit',assignedAt:iso(-120*60000),createdAt:iso(-4*86400000),history:[],dealValue:2000};
});
leads.push({...leads[0],id:'pool',phone:'0000099998',status:'Kho khách chung',stage:'PUBLIC_POOL',assignedToId:null,assigneeEmail:'',assignee:'Kho khách chung',team:undefined});
const records=[];
async function run(tree,name,group,test){try {const evidence=await test();records.push({tree,name,group,passed:true,evidence:evidence||''});}catch(error){records.push({tree,name,group,passed:false,evidence:error.message});}}
const clone=value=>JSON.parse(JSON.stringify(value));
function environment(tree){
 const memory=new Map(),cache=new Map();
 const reset=()=>{memory.clear();memory.set('sales_members.json',JSON.stringify(members));memory.set('leads.json',JSON.stringify(leads));memory.set('feature_flags.json',JSON.stringify([{key:'DATA_MASKING_SALES_AGENT',isEnabled:true},{key:'ENABLE_ROUND_ROBIN_ASSIGNMENT',isEnabled:true}]));};reset();
 const memoryFs={existsSync:file=>memory.has(path.basename(file)),readFileSync:file=>{const value=memory.get(path.basename(file));if(value===undefined)throw Error('No synthetic file');return value;},writeFileSync:(file,text)=>memory.set(path.basename(file),String(text))};
 function load(relative){
  let file=path.resolve(base,tree,relative);if(!path.extname(file))file+='.ts';
  if(cache.has(file))return cache.get(file);
  const exports={};cache.set(file,exports);
  const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
  const localRequire=id=>id==='fs'?memoryFs:id==='./firebaseDb'?{}:id.startsWith('.')?load(path.relative(path.join(base,tree),path.resolve(path.dirname(file),id))):require(id);
  new Function('exports','require','module','__dirname',code)(exports,localRequire,{exports},path.dirname(file));return exports;
 }
 function request(router,method,url,body={},token){return new Promise((resolve,reject)=>{
  let done=false;const timer=setTimeout(()=>reject(Error('Route did not finish')),3000);
  const parsed=new URL(url,'http://audit.invalid');
  const req={method,url,path:parsed.pathname,originalUrl:url,body,headers:token?{authorization:'Bearer '+token}:{},query:Object.fromEntries(parsed.searchParams),params:{},ip:'127.0.0.1',get:key=>req.headers[key.toLowerCase()]};
  const res={statusCode:200,status(code){this.statusCode=code;return this;},json(data){if(!done){done=true;clearTimeout(timer);resolve({status:this.statusCode,data:clone(data)});}return this;},send(data){return this.json(data);},setHeader(){},end(){return this.json(null);}};
  router.handle(req,res,error=>{if(!done){clearTimeout(timer);if(error)reject(error);else resolve({status:404,data:null});}});
 });}
 return {load,request,reset,memory};
}
(async()=>{
for(const tree of ['src','demo-isolated/src']){
 const env=environment(tree),db=env.load('backend/db').Database,auth=env.load('backend/auth');
 const authRouter=env.load('backend/routes/authRoutes').default,router=env.load('backend/routes/leadRoutes').default,adminRouter=env.load('backend/routes/adminRoutes').default,userRouter=env.load('backend/routes/userRoutes').default;
 const tokens={};for(const member of members){tokens[member.id]=auth.signAccessToken({userId:member.id,email:member.email,fullName:member.name,role:member.role==='admin'?'SUPER_ADMIN':member.role==='tpkd'?'TEAM_LEADER':'SALES_AGENT',teamId:member.teamId});}
 for(const member of members){await run(tree,'Login '+member.id,'authentication',async()=>{env.reset();const result=await env.request(authRouter,'POST','/login',{identifier:member.username,password});assert.equal(result.status,member.status==='paused'?403:200);if(member.status!=='paused'){tokens[member.id]=result.data.accessToken;assert.equal(result.data.user.role,member.role);assert.equal(result.data.permissions.canDeleteLeads,member.role==='admin');}return 'Role and login state checked';});}
 await run(tree,'Wrong password rejected','authentication',async()=>{const r=await env.request(authRouter,'POST','/login',{identifier:'sale-a',password:'wrong'});assert.equal(r.status,401);});
 await run(tree,'Missing credentials rejected','authentication',async()=>{const r=await env.request(authRouter,'POST','/login',{});assert.equal(r.status,400);});
 await run(tree,'Unauthenticated profile blocked','authentication',async()=>{assert.equal((await env.request(authRouter,'GET','/me')).status,401);});
 await run(tree,'Invalid token blocked on profile','authentication',async()=>{assert.equal((await env.request(authRouter,'GET','/me',{},'invalid')).status,401);});
 await run(tree,'Expired token blocked on profile','authentication',async()=>{const original=Date.now;Date.now=()=>now+9*3600000;try{assert.equal((await env.request(authRouter,'GET','/me',{},tokens['sale-a'])).status,401);}finally{Date.now=original;}});
 await run(tree,'Login response contains no password material','authentication',async()=>{const r=await env.request(authRouter,'POST','/login',{identifier:'sale-a',password});assert(!('passwordHash' in r.data.user)||!r.data.user.passwordHash,'Login response exposes passwordHash');assert(!('password' in r.data.user)||!r.data.user.password,'Login response exposes password');});
 for(const id of ['admin','manager-a','manager-b','sale-a','sale-a2','sale-b']){
  await run(tree,'List scope '+id,'authorization',async()=>{env.reset();const r=await env.request(router,'GET','/',{},tokens[id]);assert.equal(r.status,200);const member=members.find(m=>m.id===id);const expected=member.role==='admin'?leads:member.role==='tpkd'?leads.filter(l=>l.team===member.team||!l.assignee):leads.filter(l=>l.assignedToId===id||l.id==='pool');assert.deepEqual(r.data.map(l=>l.id).sort(),expected.map(l=>l.id).sort());return r.data.length+' visible customers';});
 }
 for(const id of [undefined,'invalid-token'])await run(tree,'Anonymous/invalid list blocked '+(id||'anonymous'),'authorization',async()=>{const r=await env.request(router,'GET','/',{},id==='invalid-token'?id:undefined);assert([401,403].includes(r.status),'Actual status '+r.status+', returned '+r.data.length+' customers');});
 await run(tree,'Manager missing team cannot view every team','authorization',async()=>{const r=await env.request(router,'GET','/',{},tokens['manager-no-team']);assert(!r.data.some(l=>l.assignedToId==='sale-b'),'Manager without team can see another team');});
 for(const id of ['sale-a','manager-a',undefined]){
  await run(tree,'Cross-team detail blocked '+(id||'anonymous'),'authorization',async()=>{env.reset();const r=await env.request(router,'GET','/lead-2',{},tokens[id]);assert([401,403,404].includes(r.status),'Actual status '+r.status+'; cross-team customer details returned');});
  await run(tree,'Cross-team edit blocked '+(id||'anonymous'),'authorization',async()=>{env.reset();const r=await env.request(router,'PUT','/lead-2',{notes:'Unauthorized change'},tokens[id]);assert([401,403,404].includes(r.status),'Actual status '+r.status+'; foreign customer updated');assert.notEqual(db.findLeadById('lead-2').notes,'Unauthorized change');});
  await run(tree,'Delete blocked '+(id||'anonymous'),'authorization',async()=>{env.reset();const r=await env.request(router,'DELETE','/lead-2',{},tokens[id]);assert([401,403,404].includes(r.status),'Actual status '+r.status+'; customer deleted');});
  await run(tree,'Bulk replace blocked '+(id||'anonymous'),'authorization',async()=>{env.reset();const r=await env.request(router,'POST','/',[leads[0]],tokens[id]);assert([401,403].includes(r.status),'Actual status '+r.status+'; repository reduced to '+db.getLeads().length+' customers');});
  await run(tree,'Admin audit logs blocked '+(id||'anonymous'),'authorization',async()=>{env.reset();const r=await env.request(adminRouter,'GET','/audit-logs',{},tokens[id]);assert([401,403].includes(r.status),'Actual status '+r.status+'; admin audit logs exposed');});
 }
 for(const id of ['admin','sale-a','manager-a'])await run(tree,'Permitted own edit '+id,'authorization',async()=>{env.reset();const r=await env.request(router,'PUT','/lead-0',{notes:'Allowed edit',expectedUpdatedAt:null},tokens[id]);assert.equal(r.status,200);assert.equal(db.findLeadById('lead-0').notes,'Allowed edit');});
 await run(tree,'Admin delete permitted','authorization',async()=>{env.reset();assert.equal((await env.request(router,'DELETE','/lead-0',{},tokens.admin)).status,200);assert.equal(db.findLeadById('lead-0'),null);});
 for(const id of ['sale-a','manager-a',undefined]){
  await run(tree,'Feature flags modification blocked '+(id||'anonymous'),'authorization',async()=>{env.reset();const r=await env.request(adminRouter,'PUT','/feature-flags/DATA_MASKING_SALES_AGENT',{isEnabled:false},tokens[id]);assert.equal(r.status,id?403:401);assert.equal(db.getFeatureFlags().find(flag=>flag.key==='DATA_MASKING_SALES_AGENT').isEnabled,true);});
  await run(tree,'UI customization modification blocked '+(id||'anonymous'),'authorization',async()=>{env.reset();const r=await env.request(adminRouter,'PUT','/ui-config/general',{title:'Unauthorized'},tokens[id]);assert.equal(r.status,id?403:401);});
 }
 await run(tree,'Admin feature flags permitted','authorization',async()=>{env.reset();assert.equal((await env.request(adminRouter,'PUT','/feature-flags/DATA_MASKING_SALES_AGENT',{isEnabled:false},tokens.admin)).status,200);assert.equal(db.getFeatureFlags().find(flag=>flag.key==='DATA_MASKING_SALES_AGENT').isEnabled,false);});
 await run(tree,'Concurrent edits preserve independent changes','persistence',async()=>{env.reset();const a=db.getLeads(),b=db.getLeads();a[0].phone='0000012345';await env.request(router,'POST','/',a,tokens.admin);b[1].notes='Second editor';await env.request(router,'POST','/',b,tokens['sale-a2']);assert.equal(db.findLeadById('lead-0').phone,'0000012345','Second list save overwrote first editor phone');});
 await run(tree,'Database write error propagated','persistence',()=>{const write=env.memory.set,log=console.error;env.memory.set=()=>{throw Error('Synthetic disk failure');};console.error=()=>{};try{assert.throws(()=>db.saveLeads(leads),undefined,'Database swallows write failure');}finally{env.memory.set=write;console.error=log;}});
 const workflow=env.load('utils/customerWorkflow'),csv=env.load('utils/csvHelper'),duplicates=env.load('utils/phoneDuplicateUtils'),stats=env.load('utils/crmCalculations'),sla=env.load('utils/slaUtils'),dist=env.load('services/leadDistributionService'),team=env.load('data/salesTeamData'),kpi=env.load('services/kpiReportService'),stage=env.load('backend/services/leadService');
 await run(tree,'Status counts agree with all filter results','filters',()=>{const counts=stats.calculateCRMIndicators(leads).statusCounts;for(const [status,count]of Object.entries(counts))assert.equal(count,leads.filter(l=>stats.getQuickLeadStatus(l)===status).length);assert.equal(Object.values(counts).reduce((a,b)=>a+b,0),41);});
 await run(tree,'CSV accents/email/missing name','import',()=>{const rows=csv.parseCSVToLeads('Họ và tên,SĐT,Email\nNguyễn Test,0000012345,test@audit.invalid\n,0000023456,wrong',0);assert.equal(rows[0].email,'test@audit.invalid');assert(workflow.profileIssues(rows[1]).includes('Thiếu tên'));assert(workflow.profileIssues(rows[1]).includes('Email không hợp lệ'));});
 await run(tree,'Duplicate existing and within file','import',()=>{const result=duplicates.scanBulkLeadsForDuplicates([{phone:leads[0].phone},{phone:'0000088888'},{phone:'0000088888'}],leads);assert.equal(result.duplicateCount,2);assert.equal(result.cleanItems.length,1);});
 await run(tree,'Backend import duplicate protection','import',async()=>{env.reset();const r=await env.request(router,'POST','/import',{leads:[{...leads[0],assignee:'Sale B'}],targetSaleName:'Sale B',assignTargetMode:'single_sale',duplicateHandlingMode:'skip_protect_old_sale'},tokens.admin);assert.equal(r.status,200);assert.equal(db.getLeads().length,41);assert.equal(db.findLeadById('lead-0').assignee,'Sale A');});
 await run(tree,'Empty import rejected','import',async()=>{assert.equal((await env.request(router,'POST','/import',{leads:[]},tokens.admin)).status,400);});
 await run(tree,'Invalid phone create rejected','import',async()=>{assert.equal((await env.request(router,'POST','/',{fullName:'Synthetic',phone:'123'},tokens.admin)).status,400);});
 await run(tree,'Quality warnings and completed profile','profile',()=>{assert.deepEqual(workflow.profileIssues(leads[0]),[]);assert(workflow.profileIssues({...leads[0],phone:'123',email:'bad',budget:''}).length>=3);});
 await run(tree,'Empty CSV returns no staged customers','import',()=>{assert.deepEqual(csv.parseCSVToLeads('',0),[]);});
 await run(tree,'Empty customer list returns zero indicators','filters',()=>{const r=stats.calculateCRMIndicators([]);assert.equal(r.totalLeads,0);assert.equal(r.closeRate,0);assert(Object.values(r.statusCounts).every(count=>count===0));});
 await run(tree,'Unknown status falls into Other','filters',()=>{assert.equal(stats.getQuickLeadStatus({...leads[0],status:'Unknown state',callStatus:undefined}),'Khác');});
 await run(tree,'Neglected customer recent care and reminder','profile',()=>{const l={...leads[0],status:'Quan tâm',assignedAt:iso(-4*86400000)};assert(workflow.neglectedCustomer(l,now));assert(!workflow.neglectedCustomer({...l,status:'Đã chốt'},now));assert(!workflow.neglectedCustomer({...l,callbackReminder:{status:'pending'}},now));assert(!workflow.neglectedCustomer({...l,history:[{type:'Cuộc gọi',date:iso(-60000)}]},now));});
 await run(tree,'Audit old/new field values','profile',()=>{assert.equal(workflow.describeLeadChanges(leads[0],{...leads[0],phone:'0000077777',assignee:'Sale B'}).length,2);});
 for(const member of members.filter(m=>m.role==='sale'||m.role==='tpkd'))await run(tree,'Appointment conflict '+member.id,'appointments',()=>{const a={date:'2026-10-03',time:'09:00',assignee:member.name,status:'Chờ đi xem'};assert.equal(workflow.appointmentConflicts({...a,time:'09:30'},[a]).length,1);assert.equal(workflow.appointmentConflicts({...a,time:'10:00'},[a]).length,0);assert.equal(workflow.appointmentConflicts(a,[{...a,status:'Đã huỷ'}]).length,0);assert.equal(workflow.appointmentConflicts(a,[{...a,assignee:'Someone Else'}]).length,0);});
 await run(tree,'SLA acceptance alone is not care','sla',()=>{const l={...leads[0],assignedAt:iso(-60000),acceptedAt:iso(-30000),history:[{type:'Ghi chú nội bộ',author:'Sale A',content:'Đã tiếp nhận'}]};assert.notEqual(sla.getLeadSlaInfo(l,dist.DEFAULT_DISTRIBUTION_POLICY,now).status,'completed','Acceptance note completes care SLA');});
 await run(tree,'Reassigned customer receives fresh SLA','sla',()=>{const result=dist.checkAndReassignSlaLeads([{...leads[0],history:[]}],members,dist.DEFAULT_DISTRIBUTION_POLICY);assert(result.reassignedLeads.length);assert.equal(result.updatedLeads[0].slaBreached,false,'New owner inherits breach flag');});
 await run(tree,'SLA reclaim excludes admin','sla',()=>{const result=dist.checkAndReassignSlaLeads([{...leads[0]}],[members[0],members[3]],dist.DEFAULT_DISTRIBUTION_POLICY);assert(!result.updatedLeads.some(l=>l.assignee==='Admin Test'),'Reclaim assigned customer to Admin');});
 await run(tree,'Redistribution resets assigned/accepted timestamp','sla',()=>{const old={...leads[0],acceptedAt:iso(-60000)};const r=team.distributeLeadsToSales([old],[members[4]]).distributedLeads[0];assert.notEqual(r.assignedAt,old.assignedAt,'Old assignment timestamp retained');assert.equal(r.acceptedAt,undefined);assert.equal(r.assignedToId,members[4].id);});
 await run(tree,'No SLA breach without known assignment time','sla',()=>{const l={...leads[0],assignedAt:undefined};assert.equal(sla.getLeadSlaInfo(l,dist.DEFAULT_DISTRIBUTION_POLICY,now).isBreached,false,'UI derives overdue SLA from creation time');});
 await run(tree,'Distribution honors offline/maxDailyLeads','distribution',()=>{const offline={...members[3],isOnlineForLead:false};const full={...members[4],maxDailyLeads:0};const r=dist.distributeLeadsSmartly([leads[0]],[offline,full],dist.DEFAULT_DISTRIBUTION_POLICY,leads);assert.deepEqual(r.countPerSale,{},'Offline/zero quota must produce no assignments');assert.deepEqual(r.distributedLeads,[leads[0]],'Ineligible distribution must preserve original customers');});
 await run(tree,'Performance does not count assignment note as acceptance','distribution',()=>{const r=dist.calculateSalesPerformance([members[3]],[{...leads[0],history:[{type:'Ghi chú nội bộ',author:'Hệ thống tự động',content:'Phân bổ'}]}])[0];assert.equal(r.acceptedCount,0,'Assignment history counts as accepted');assert.equal(r.reportedCount,0);});
 await run(tree,'Source Zalo is not proof of connection','kpi',()=>{assert.equal(kpi.isLeadZaloConnected({...leads[0],zaloConnected:false,dataSource:'Zalo Ads'}),false,'Zalo source counted as connected');});
 await run(tree,'Negative Zalo note is not proof','kpi',()=>{assert.equal(kpi.isLeadZaloConnected({...leads[0],zaloConnected:false,history:[{type:'Ghi chú nội bộ',content:'Chưa kết nối Zalo'}]}),false,'Negative note counted as connected');});
 await run(tree,'Confirmed Zalo counts correctly','kpi',()=>{assert.equal(kpi.isLeadZaloConnected({...leads[0],zaloConnected:true,zaloConnectedAt:iso(0)}),true);});
 await run(tree,'Frontend closed/negotiating statuses map to backend','kpi',()=>{assert.equal(stage.mapDisplayToStage('Đã chốt'),'WON','Đã chốt maps to NEW_LEAD');assert.equal(stage.mapDisplayToStage('Đàm phán / Cọc'),'PROPOSAL');});
 await run(tree,'Won API idempotent revenue','kpi',async()=>{env.reset();for(let i=0;i<2;i++)assert.equal((await env.request(router,'PATCH','/lead-0/stage',{stage:'WON',actualValue:1000},tokens.admin)).status,200);assert.equal(db.getUserKpiTarget('sale-a',new Date().getMonth()+1,new Date().getFullYear()).achievedDeals,1,'Repeated WON request credits two deals');});
 await run(tree,'Missing deal value does not invent revenue','kpi',async()=>{env.reset();await env.request(router,'PATCH','/lead-0/stage',{stage:'WON'},tokens.admin);assert.equal(db.getUserKpiTarget('sale-a',new Date().getMonth()+1,new Date().getFullYear()).achievedRevenue,0,'Absent value credited as 100 million');});
 for(const id of ['sale-a','manager-a',undefined])await run(tree,'Role escalation blocked '+(id||'anonymous'),'authorization',async()=>{env.reset();const r=await env.request(userRouter,'PUT','/sale-a',{role:'admin'},tokens[id]);assert([401,403].includes(r.status),'Actual status '+r.status+'; changed NVKD to Admin');});
 await run(tree,'User list hides password hashes','authentication',async()=>{env.reset();const r=await env.request(userRouter,'GET','/',{},tokens.admin);assert.equal(r.status,200);const list=Array.isArray(r.data)?r.data:r.data.users;assert(list.every(user=>!user.passwordHash&&!user.password));});
 await run(tree,'Disabled account old JWT blocked','authorization',async()=>{env.reset();const r=await env.request(router,'GET','/',{},tokens.paused);assert([401,403].includes(r.status),'Inactive account JWT still accepted');});
 await run(tree,'KPI day uses Vietnam date at midnight','kpi',()=>{const member=members[3],reference=new Date('2026-10-03T00:30:00+07:00');const l={...leads[0],zaloConnected:true,zaloConnectedAt:'2026-10-03T00:10:00+07:00'};const report=kpi.calculateWeeklyKpiReports([member],[l],[],kpi.DEFAULT_KPI_POLICY,reference)[0];assert.equal(report.dailyZaloCountToday,1,'Midnight Vietnam connection assigned to wrong day');});
 await run(tree,'Closed status alone is not meeting evidence','kpi',()=>{const report=kpi.calculateWeeklyKpiReports([members[3]],[{...leads[0],date:'2026-09-30',status:'Đã chốt'}],[],kpi.DEFAULT_KPI_POLICY,new Date('2026-10-03T12:00:00+07:00'))[0];assert.equal(report.weeklyMeetingCount,0,'Closed customer counted as a meeting without appointment');});
 for(const id of ['admin','manager-a','sale-a'])await run(tree,'Confirmed meeting report '+id,'kpi',()=>{const member=members.find(m=>m.id===id);if(member.role==='admin')return 'Admin is excluded from individual sales KPI by policy';const l={...leads[0],assignee:member.name,date:'2026-01-01',status:'Khách mới'};const app={leadId:l.id,assignee:member.name,date:'2026-09-30',time:'09:00',status:'Đã xem'};const report=kpi.calculateWeeklyKpiReports([member],[l],[app],kpi.DEFAULT_KPI_POLICY,new Date('2026-10-03T12:00:00+07:00'))[0];assert.equal(report.weeklyMeetingCount,1);});
 await run(tree,'Backend reassignment resets acceptance and email','import',async()=>{env.reset();db.upsertLead({...leads[0],acceptedAt:iso(-60000),firstReportedAt:iso(-30000)});await env.request(router,'POST','/import',{leads:[leads[0]],targetUserId:'sale-b',assignTargetMode:'single_sale',duplicateHandlingMode:'reassign_to_new_sale'},tokens.admin);const updated=db.findLeadById('lead-0');assert.equal(updated.assigneeEmail,'sale-b@audit.invalid','Backend reassignment leaves old email');assert.equal(updated.acceptedAt,undefined);assert.equal(updated.firstReportedAt,undefined);});
 await run(tree,'Cancelled appointment cannot conflict','appointments',()=>{assert.equal(workflow.appointmentConflicts({date:'2026-10-03',time:'09:00',assignee:'Sale A'},[{date:'2026-10-03',time:'09:00',assignee:'Sale A',status:'Đã huỷ'}]).length,0);});
 await run(tree,'Cross-midnight appointment conflict','appointments',()=>{assert.equal(workflow.appointmentConflicts({date:'2026-10-04',time:'00:10',assignee:'Sale A'},[{date:'2026-10-03',time:'23:45',assignee:'Sale A',status:'Chờ đi xem'}]).length,1);});
 await run(tree,'Completed care excludes SLA reclaim','sla',()=>{const l={...leads[0],acceptedAt:iso(-60000),firstReportedAt:iso(-30000)};assert.equal(sla.getLeadSlaInfo(l,dist.DEFAULT_DISTRIBUTION_POLICY,now).status,'completed');assert.equal(dist.checkAndReassignSlaLeads([l],members,dist.DEFAULT_DISTRIBUTION_POLICY).reassignedLeads.length,0);});
 await run(tree,'Frontend own scope survives employee rename','frontend scope',()=>{const app=fs.readFileSync(path.join(base,tree,'App.tsx'),'utf8');const start=app.indexOf('  const authorizedLeads = useMemo(() => {')+'  const authorizedLeads = useMemo(() => {'.length;const end=app.indexOf('  }, [leads, currentUser, departmentMemberNames]);',start);const filter=new Function('leads','currentUser','departmentMemberNames',app.slice(start,end));const visible=filter([leads[0]],{...members[3],name:'Renamed Sale A'},new Set());assert.equal(visible.length,1,'Frontend ignores assignedToId after employee rename');});
 await run(tree,'No missing-manager fallback leaks team membership','frontend scope',()=>{const orphan={...members[5],managerId:undefined,managerEmail:undefined,team:undefined};const found=team.getTpkdForMember(orphan,members);assert(!found,'Missing manager assigned to default TPKD');});
 const kpiRouter=env.load('backend/routes/kpiRoutes').default;
 await run(tree,'Unauthenticated personnel list blocked','authorization',async()=>{assert.equal((await env.request(userRouter,'GET','/')).status,401);});
 for(const id of ['sale-a','manager-a']){
  await run(tree,'Cross-team status and activity blocked '+id,'authorization',async()=>{env.reset();assert.equal((await env.request(router,'PATCH','/lead-2/status',{status:'Đã chốt',expectedUpdatedAt:null},tokens[id])).status,403);assert.equal((await env.request(router,'POST','/lead-2/activities',{type:'CALL',content:'Synthetic call'},tokens[id])).status,403);});
  await run(tree,'Cross-team KPI access blocked '+id,'authorization',async()=>{assert.equal((await env.request(kpiRouter,'GET','/?userId=sale-b',{},tokens[id])).status,403);});
 }
 await run(tree,'PUT without version rejected','persistence',async()=>{env.reset();assert.equal((await env.request(router,'PUT','/lead-0',{notes:'Unsafe'},tokens.admin)).status,428);assert.equal(db.findLeadById('lead-0').notes,leads[0].notes);});
 await run(tree,'Two admins stale bulk save rejected','persistence',async()=>{env.reset();const first=db.getLeads(),second=db.getLeads();first[0].notes='First admin';assert.equal((await env.request(router,'POST','/',first,tokens.admin)).status,200);second[1].notes='Second admin';assert.equal((await env.request(router,'POST','/',second,tokens.admin)).status,409);assert.equal(db.findLeadById('lead-0').notes,'First admin');});
 await run(tree,'Same customer stale PUT rejected','persistence',async()=>{env.reset();assert.equal((await env.request(router,'PUT','/lead-0',{notes:'First edit',expectedUpdatedAt:null},tokens.admin)).status,200);assert.equal((await env.request(router,'PUT','/lead-0',{notes:'Stale edit',expectedUpdatedAt:null},tokens.admin)).status,409);assert.equal(db.findLeadById('lead-0').notes,'First edit');});
 await run(tree,'Sales creation cannot assign another owner','authorization',async()=>{env.reset();const r=await env.request(router,'POST','/',{id:'synthetic-new',fullName:'Synthetic New',phone:'0000076543',assignedToId:'sale-b',assignee:'Sale B'},tokens['sale-a']);assert.equal(r.status,201);assert.equal(r.data.lead.assignedToId,'sale-a');assert.equal(r.data.lead.assigneeEmail,members[3].email);});
 await run(tree,'Manager import cannot transfer cross-team customer','authorization',async()=>{env.reset();const r=await env.request(router,'POST','/import',{leads:[leads[2]],targetUserId:'sale-a',assignTargetMode:'single_sale',duplicateHandlingMode:'reassign_to_new_sale'},tokens['manager-a']);assert.equal(r.status,403);assert.equal(db.findLeadById('lead-2').assignedToId,'sale-b');});
 await run(tree,'Batch distribution respects daily capacity','distribution',()=>{const owner={...members[3],maxDailyLeads:2};const input=Array.from({length:5},(_,i)=>({...leads[0],id:'batch-'+i,assignee:'Chưa phân công',assignedToId:undefined,assignedAt:undefined}));const result=dist.distributeLeadsSmartly(input,[owner],dist.DEFAULT_DISTRIBUTION_POLICY,[]);assert.equal(result.countPerSale[owner.name],2);assert.equal(result.distributedLeads.filter(l=>l.assignedToId===owner.id).length,2);});
 await run(tree,'Report SLA starts at acceptance','sla',()=>{const lead={...leads[0],assignedAt:iso(-5*3600000),acceptedAt:iso(-3600000)};assert.equal(sla.getLeadSlaInfo(lead,dist.DEFAULT_DISTRIBUTION_POLICY,now).isBreached,false);assert.equal(dist.checkAndReassignSlaLeads([lead],members,dist.DEFAULT_DISTRIBUTION_POLICY).reassignedLeads.length,0);});
 await run(tree,'Actual call records first care timestamp','sla',async()=>{env.reset();const result=await env.request(router,'POST','/lead-0/activities',{type:'CALL',content:'Synthetic call result'},tokens['sale-a']);assert.equal(result.status,200);assert(db.findLeadById('lead-0').firstReportedAt);});
 await run(tree,'Status and PUT closures have consistent revenue','kpi',async()=>{env.reset();assert.equal((await env.request(router,'PATCH','/lead-0/status',{status:'Đã chốt',expectedUpdatedAt:null},tokens.admin)).status,200);const current=db.findLeadById('lead-0');assert.equal((await env.request(router,'PUT','/lead-0',{actualValue:2500,expectedUpdatedAt:current.updatedAt},tokens.admin)).status,200);const target=db.getUserKpiTarget('sale-a',new Date().getMonth()+1,new Date().getFullYear());assert.equal(target.achievedDeals,1);assert.equal(target.achievedRevenue,2500);});
 await run(tree,'Reopen and close cannot double credit a deal','kpi',async()=>{env.reset();for(const stage of ['WON','LOST','WON'])assert.equal((await env.request(router,'PATCH','/lead-0/stage',{stage,actualValue:1000},tokens.admin)).status,200);const target=db.getUserKpiTarget('sale-a',new Date().getMonth()+1,new Date().getFullYear());assert.equal(target.achievedDeals,1);assert.equal(target.achievedRevenue,1000);});
 // Connect the actual browser service to the actual router without a network server.
 const storage=new Map();global.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,String(value)),removeItem:key=>storage.delete(key)};
 const tracker=env.load('services/saveTracker');
 const Service=env.load('services/crmBackendService').CRMBackendService;
 const requests=[];
 global.fetch=async(url,options={})=>{
  const parsed=new URL(url,'http://audit.invalid');requests.push({url:parsed.pathname,method:options.method||'GET',body:options.body&&JSON.parse(options.body)});
  const r=await env.request(parsed.pathname.startsWith('/api/auth')?authRouter:router,options.method||'GET',parsed.pathname.replace(/^\/api\/(leads|auth)/,'')||'/',options.body?JSON.parse(options.body):{},String(options.headers?.Authorization||'').replace(/^Bearer /,''));
  return {ok:r.status>=200&&r.status<300,status:r.status,statusText:String(r.status),json:async()=>clone(r.data),text:async()=>JSON.stringify(r.data),headers:{forEach(){}}};
 };
 await run(tree,'Login stores real server session token','frontend authentication',async()=>{env.reset();storage.clear();const api=env.load('services/salesMembersApi');const result=await api.loginEmployee('sale-a',password);assert.equal(result.success,true);assert(storage.get('salepro_token'));assert.equal(auth.verifyAccessToken(storage.get('salepro_token')).userId,'sale-a');});
 await run(tree,'Client saves only changed customer fields','persistence',async()=>{env.reset();tracker.resetSaveTracking();storage.set('salepro_token',tokens.admin);requests.length=0;const client=new Service();const list=await client.getLeads();const edited=list.map(l=>l.id==='lead-0'?{...l,notes:'Changed via client'}:l);assert.equal(await client.saveLeads(edited),true);const writes=requests.filter(r=>r.method!=='GET');assert.equal(writes.length,1);assert.equal(writes[0].method,'PUT');assert.deepEqual(Object.keys(writes[0].body).sort(),['expectedUpdatedAt','notes']);assert.equal(db.findLeadById('lead-0').notes,'Changed via client');});
 await run(tree,'Two clients preserve different customer edits','persistence',async()=>{env.reset();tracker.resetSaveTracking();storage.set('salepro_token',tokens.admin);const a=new Service(),b=new Service();const first=await a.getLeads(),second=await b.getLeads();assert.equal(await a.updateLead({...first.find(l=>l.id==='lead-0'),notes:'Client A'}),true);assert.equal(await b.updateLead({...second.find(l=>l.id==='lead-1'),notes:'Client B'}),true);assert.equal(db.findLeadById('lead-0').notes,'Client A');assert.equal(db.findLeadById('lead-1').notes,'Client B');});
 await run(tree,'Two clients cannot overwrite same customer','persistence',async()=>{env.reset();tracker.resetSaveTracking();storage.set('salepro_token',tokens.admin);const a=new Service(),b=new Service();const first=await a.getLeads(),second=await b.getLeads();assert.equal(await a.updateLead({...first.find(l=>l.id==='lead-0'),notes:'Client A'}),true);assert.equal(await b.updateLead({...second.find(l=>l.id==='lead-0'),notes:'Client B'}),false);assert.equal(db.findLeadById('lead-0').notes,'Client A');assert(tracker.getSaveState().failed);});
 await run(tree,'Client does not upload initial cached list','persistence',async()=>{tracker.resetSaveTracking();requests.length=0;const client=new Service();assert.equal(await client.saveLeads(leads),false);assert.equal(requests.length,0);});
 await run(tree,'Client accepts empty authorized server list','persistence',async()=>{env.reset();tracker.resetSaveTracking();storage.set('salepro_token',tokens.admin);db.saveLeads([]);const client=new Service();assert.deepEqual(await client.getLeads(),[]);assert.equal(await client.saveLeads([]),true);});
 await run(tree,'Client rejects stale edits after account switch','authorization',async()=>{env.reset();tracker.resetSaveTracking();storage.set('salepro_token',tokens.admin);const client=new Service();const list=await client.getLeads();storage.set('salepro_token',tokens['sale-b']);assert.equal(await client.updateLead({...list.find(l=>l.id==='lead-0'),notes:'Stale session'}),false);assert.equal(db.findLeadById('lead-0').notes,leads[0].notes);});
 await run(tree,'Initial skipped save does not block first server snapshot','persistence',async()=>{env.reset();tracker.resetSaveTracking();storage.set('salepro_token',tokens.admin);const client=new Service();assert.equal(await client.saveLeads(leads),false);assert.equal(tracker.getSaveState().failed,0);const list=await client.getLeads();assert.equal(await client.updateLead({...list.find(l=>l.id==='lead-0'),notes:'First real edit'}),true);});
 await run(tree,'Explicit refresh resolves stale version for next edit','persistence',async()=>{env.reset();tracker.resetSaveTracking();storage.set('salepro_token',tokens.admin);const client=new Service();const list=await client.getLeads();db.upsertLead({...leads[0],notes:'Other editor'});assert.equal(await client.updateLead({...list.find(l=>l.id==='lead-0'),notes:'Stale'}),false);const fresh=await client.getLeads(true);tracker.resetSaveTracking();assert.equal(await client.updateLead({...fresh.find(l=>l.id==='lead-0'),notes:'Reviewed fresh edit'}),true);});
 await run(tree,'New deal preserves previous KPI totals','kpi',async()=>{env.reset();const month=new Date().getMonth()+1,year=new Date().getFullYear();db.upsertKpiTarget({userId:'sale-a',month,year,achievedRevenue:5000,achievedDeals:5});await env.request(router,'PATCH','/lead-0/stage',{stage:'WON',actualValue:1000},tokens.admin);const target=db.getUserKpiTarget('sale-a',month,year);assert.equal(target.achievedRevenue,6000);assert.equal(target.achievedDeals,6);});
 await run(tree,'Round robin honors batch capacity','distribution',()=>{const owner={...members[3],maxDailyLeads:2};const input=Array.from({length:5},(_,i)=>({...leads[0],id:'batch-'+i,assignee:'Chưa phân công',assignedToId:undefined,assignedAt:undefined}));assert.equal(team.distributeLeadsToSales(input,[owner]).countPerSale[owner.name],2);});
 const serverPath=path.join(base,tree==='src'?'server.ts':'demo-isolated/server.ts');
 const serverSource=ts.createSourceFile(serverPath,fs.readFileSync(serverPath,'utf8'),ts.ScriptTarget.ES2022,true);
 const legacyPaths=new Set(['/api/sales-members','/api/sales-members/reset-to-official','/api/database/export','/api/database/restore','/api/logs']);
 const legacyCalls=[];function visit(node){if(ts.isCallExpression(node)&&ts.isPropertyAccessExpression(node.expression)&&node.expression.expression.getText(serverSource)==='app'&&ts.isStringLiteral(node.arguments[0])&&legacyPaths.has(node.arguments[0].text))legacyCalls.push(node.getText(serverSource));ts.forEachChild(node,visit);}visit(serverSource);
 const legacy=require('express').Router(),middleware=env.load('backend/middleware');
 const legacyCode=ts.transpileModule(legacyCalls.join(';\n'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
 new Function('app','authenticateToken','requireSuperAdmin','getStoredSalesMembers',legacyCode)(legacy,middleware.authenticateToken,middleware.requireSuperAdmin,()=>clone(members));
 for(const id of ['sale-a','manager-a',undefined])await run(tree,'Legacy administration routes protected '+(id||'anonymous'),'authorization',async()=>{env.reset();for(const [method,url] of [['POST','/api/sales-members'],['POST','/api/sales-members/reset-to-official'],['GET','/api/database/export'],['POST','/api/database/restore'],['GET','/api/logs'],['DELETE','/api/logs']]){const r=await env.request(legacy,method,url,{role:'admin'},tokens[id]);assert([401,403].includes(r.status),method+' '+url+' allows '+id);}});
 await run(tree,'Legacy personnel response hides password material','authentication',async()=>{env.reset();const r=await env.request(legacy,'GET','/api/sales-members',{},tokens.admin);assert.equal(r.status,200);assert(r.data.every(member=>!member.password&&!member.passwordHash));assert.equal((await env.request(legacy,'GET','/api/sales-members')).status,401);});
 await run(tree,'KPI week follows Vietnam date on UTC host','kpi',()=>{const timezone=process.env.TZ;process.env.TZ='UTC';try{assert.equal(kpi.getCurrentWeekRange(new Date('2026-10-05T00:30:00+07:00')).startStr,'2026-10-05');}finally{process.env.TZ=timezone;}});
}
const summary={total:records.length,passed:records.filter(r=>r.passed).length,failed:records.filter(r=>!r.passed).length};
fs.writeFileSync(path.join(output,'audit.json'),JSON.stringify({generatedAt:new Date().toISOString(),scope:'Actual routers, JWT/bcrypt, real Database with memory-only filesystem, and business functions. No live HTTP deployment or browser UI tested.',syntheticData:{members:members.length,customers:leads.length,teams:2},summary,tests:records},null,2));
const markdown=['# CRM source audit', '',`Checks: ${summary.total}; passed: ${summary.passed}; failed: ${summary.failed}.`, '', 'Synthetic fixtures: 8 accounts, 41 customers, 2 teams. Repository file I/O runs entirely in memory; customer files were not modified.', '', 'Actual Express routers are invoked in process with real JWT middleware and database methods. Live deployment, browser rendering and external mail/Zalo services are outside this test scope.', '', '| Tree | Group | Test | Result | Evidence |','|---|---|---|---|---|',...records.map(r=>`| ${r.tree} | ${r.group} | ${r.name} | ${r.passed?'PASS':'FAIL'} | ${String(r.evidence).replace(/\n/g,' ').replace(/\|/g,'/').slice(0,350)} |`)];fs.writeFileSync(path.join(output,'audit.md'),markdown.join('\n'));
console.log(JSON.stringify(summary));console.log('Report: audit-results/audit.md');
process.exitCode=summary.failed?1:0;
})().catch(error=>{console.error(error);process.exitCode=2;});
